# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setObjectName("port_label")
        self.horizontalLayout_2.addWidget(self.port_label)
        self.udp_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.udp_bt.sizePolicy().hasHeightForWidth())
        self.udp_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.udp_bt.setFont(font)
        self.udp_bt.setObjectName("udp_bt")
        self.horizontalLayout_2.addWidget(self.udp_bt)
        self.inputport_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.inputport_txt.setObjectName("inputport_txt")
        self.horizontalLayout_2.addWidget(self.inputport_txt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(24)
        self.logo.setFont(font)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.playbt_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playbt_label.sizePolicy().hasHeightForWidth())
        self.playbt_label.setSizePolicy(sizePolicy)
        self.playbt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.playbt_label.setObjectName("playbt_label")
        self.horizontalLayout_4.addWidget(self.playbt_label)
        self.message_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_label.sizePolicy().hasHeightForWidth())
        self.message_label.setSizePolicy(sizePolicy)
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setObjectName("message_label")
        self.horizontalLayout_4.addWidget(self.message_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.udp_label = QtWidgets.QLabel(self.centralwidget)
        self.udp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.udp_label.setObjectName("udp_label")
        self.verticalLayout_4.addWidget(self.udp_label)
        self.play_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.play_bar.setProperty("value", 24)
        self.play_bar.setObjectName("play_bar")
        self.verticalLayout_4.addWidget(self.play_bar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.play_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_bt.sizePolicy().hasHeightForWidth())
        self.play_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.play_bt.setFont(font)
        self.play_bt.setObjectName("play_bt")
        self.horizontalLayout_3.addWidget(self.play_bt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.nvidia_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nvidia_label.sizePolicy().hasHeightForWidth())
        self.nvidia_label.setSizePolicy(sizePolicy)
        self.nvidia_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nvidia_label.setObjectName("nvidia_label")
        self.horizontalLayout_5.addWidget(self.nvidia_label)
        self.audiopro_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audiopro_label.sizePolicy().hasHeightForWidth())
        self.audiopro_label.setSizePolicy(sizePolicy)
        self.audiopro_label.setAlignment(QtCore.Qt.AlignCenter)
        self.audiopro_label.setObjectName("audiopro_label")
        self.horizontalLayout_5.addWidget(self.audiopro_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fre_anal_label = QtWidgets.QLabel(self.centralwidget)
        self.fre_anal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fre_anal_label.setObjectName("fre_anal_label")
        self.verticalLayout_2.addWidget(self.fre_anal_label)
        self.FFT_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FFT_bt.sizePolicy().hasHeightForWidth())
        self.FFT_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.FFT_bt.setFont(font)
        self.FFT_bt.setObjectName("FFT_bt")
        self.verticalLayout_2.addWidget(self.FFT_bt)
        self.dynamic_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dynamic_bt.sizePolicy().hasHeightForWidth())
        self.dynamic_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dynamic_bt.setFont(font)
        self.dynamic_bt.setObjectName("dynamic_bt")
        self.verticalLayout_2.addWidget(self.dynamic_bt)
        self.CQT_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CQT_bt.sizePolicy().hasHeightForWidth())
        self.CQT_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.CQT_bt.setFont(font)
        self.CQT_bt.setObjectName("CQT_bt")
        self.verticalLayout_2.addWidget(self.CQT_bt)
        self.stft_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stft_bt.sizePolicy().hasHeightForWidth())
        self.stft_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.stft_bt.setFont(font)
        self.stft_bt.setObjectName("stft_bt")
        self.verticalLayout_2.addWidget(self.stft_bt)
        self.rmse_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rmse_bt.sizePolicy().hasHeightForWidth())
        self.rmse_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rmse_bt.setFont(font)
        self.rmse_bt.setObjectName("rmse_bt")
        self.verticalLayout_2.addWidget(self.rmse_bt)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.fea_extra_label = QtWidgets.QLabel(self.centralwidget)
        self.fea_extra_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fea_extra_label.setObjectName("fea_extra_label")
        self.verticalLayout.addWidget(self.fea_extra_label)
        self.mel_spec_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mel_spec_bt.sizePolicy().hasHeightForWidth())
        self.mel_spec_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.mel_spec_bt.setFont(font)
        self.mel_spec_bt.setObjectName("mel_spec_bt")
        self.verticalLayout.addWidget(self.mel_spec_bt)
        self.mfcc_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mfcc_bt.sizePolicy().hasHeightForWidth())
        self.mfcc_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.mfcc_bt.setFont(font)
        self.mfcc_bt.setObjectName("mfcc_bt")
        self.verticalLayout.addWidget(self.mfcc_bt)
        self.poly_feature_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.poly_feature_bt.sizePolicy().hasHeightForWidth())
        self.poly_feature_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.poly_feature_bt.setFont(font)
        self.poly_feature_bt.setObjectName("poly_feature_bt")
        self.verticalLayout.addWidget(self.poly_feature_bt)
        self.tonnetz_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tonnetz_bt.sizePolicy().hasHeightForWidth())
        self.tonnetz_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tonnetz_bt.setFont(font)
        self.tonnetz_bt.setObjectName("tonnetz_bt")
        self.verticalLayout.addWidget(self.tonnetz_bt)
        self.AI_bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AI_bt.sizePolicy().hasHeightForWidth())
        self.AI_bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura LT Book")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AI_bt.setFont(font)
        self.AI_bt.setObjectName("AI_bt")
        self.verticalLayout.addWidget(self.AI_bt)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 24))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionSave)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.port_label.setText(_translate("MainWindow", "Port:"))
        self.udp_bt.setText(_translate("MainWindow", "Connect"))
        self.inputport_txt.setText(_translate("MainWindow", "7777"))
        self.logo.setText(_translate("MainWindow", "LOGO"))
        self.playbt_label.setText(_translate("MainWindow", "GIF"))
        self.message_label.setText(_translate("MainWindow", "Message"))
        self.udp_label.setText(_translate("MainWindow", "传输与播放"))
        self.play_bt.setText(_translate("MainWindow", "Play"))
        self.nvidia_label.setText(_translate("MainWindow", "NVIDIA"))
        self.audiopro_label.setText(_translate("MainWindow", "Audio Processing"))
        self.fre_anal_label.setText(_translate("MainWindow", "频域分析"))
        self.FFT_bt.setText(_translate("MainWindow", "FFT"))
        self.dynamic_bt.setText(_translate("MainWindow", "Dynamic"))
        self.CQT_bt.setText(_translate("MainWindow", "CQT"))
        self.stft_bt.setText(_translate("MainWindow", "STFT"))
        self.rmse_bt.setText(_translate("MainWindow", "RMSE"))
        self.fea_extra_label.setText(_translate("MainWindow", "特征提取"))
        self.mel_spec_bt.setText(_translate("MainWindow", "Mel Spec"))
        self.mfcc_bt.setText(_translate("MainWindow", "MFCC"))
        self.poly_feature_bt.setText(_translate("MainWindow", "Poly"))
        self.tonnetz_bt.setText(_translate("MainWindow", "TONNETZ"))
        self.AI_bt.setText(_translate("MainWindow", "AI"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

